spring.application.name=ecommerce-api

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=1234567w

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Dialect (Uyumlu hale getirildi)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Debug Hibernate
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# Optional: Server Port (Değiştirmek istersen)
# server.port=8080
